# oag configuration — SSE Chat example
# Generates both a Node client and React/SWR client with SSE streaming hooks
# from the AI Chat API OpenAPI 3.2 spec.
input: ../../crates/oag-core/tests/fixtures/sse-chat.yaml

naming:
  strategy: use_operation_id
  aliases: {}

generators:
  node-client:
    output: generated/node
    layout: modular
    base_url: https://api.example.com/v1
    scaffold:
      package_name: "@examples/sse-chat-node-client"
      repository: https://github.com/urmzd/openapi-generator
      formatter: biome
      test_runner: vitest
      bundler: tsdown

  react-swr-client:
    output: generated/react
    layout: modular
    base_url: https://api.example.com/v1
    scaffold:
      package_name: "@examples/sse-chat-react-client"
      repository: https://github.com/urmzd/openapi-generator
      formatter: biome
      test_runner: vitest
      bundler: tsdown
